AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'kinesis-consumer

  Sample SAM Template for kinesis-consumer

  '
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: 24
      StreamModeDetails:
        StreamMode: ON_DEMAND
  ConsumerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      SamResourceId: ConsumerFunction
    Properties:
      CodeUri: ConsumerFunction
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
      - arm64
